# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhJiraChangelog < Formula
  desc "Changelog generator using jira issues"
  homepage "https://github.com/HandOfGod94/gh-jira-changelog"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HandOfGod94/gh-jira-changelog/releases/download/v0.3.0/gh-jira-changelog_v0.3.0_darwin-arm64"
      sha256 "33890aa1b6747291890bb7b59ae03eeaa17c4e464fd695a5477c62630af0e6e8"

      def install
        bin.install "gh-jira-changelog_v0.3.0_darwin-arm64" => "gh-jira-changelog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HandOfGod94/gh-jira-changelog/releases/download/v0.3.0/gh-jira-changelog_v0.3.0_darwin-amd64"
      sha256 "1bb1cafb479885acae6f1075a190d3cb3f939a4fadc2ae8fcd263d5a73ca59ae"

      def install
        bin.install "gh-jira-changelog_v0.3.0_darwin-amd64" => "gh-jira-changelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HandOfGod94/gh-jira-changelog/releases/download/v0.3.0/gh-jira-changelog_v0.3.0_linux-amd64"
      sha256 "67c3c89bfe836427b2a32ec2a890380d08aed53b981ab1af9dad1fb4fa4925b0"

      def install
        bin.install "gh-jira-changelog_v0.3.0_linux-amd64" => "gh-jira-changelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HandOfGod94/gh-jira-changelog/releases/download/v0.3.0/gh-jira-changelog_v0.3.0_linux-arm64"
      sha256 "f25e568f02a7d9492ed7db0f85ab2dae60808d2163431382872e8c8d26be7b1c"

      def install
        bin.install "gh-jira-changelog_v0.3.0_linux-arm64" => "gh-jira-changelog"
      end
    end
  end
end
