# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkatail < Formula
  desc "tail kafka logs from any topic, any wire format on local console"
  homepage "https://github.com/HandOfGod94/kafkatail"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HandOfGod94/kafkatail/releases/download/v0.1.3/kafkatail_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "933b99b54fe724c85bd4e89fd3213f5c52fe5058d6d2eb4d02d3861b7f1f5ca2"

      def install
        bin.install "kafkatail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HandOfGod94/kafkatail/releases/download/v0.1.3/kafkatail_0.1.3_Darwin_arm64.tar.gz"
      sha256 "433570aed0c5f1eaf003a4e2405e91b0e9751ea8d7db831766449e8d60e61636"

      def install
        bin.install "kafkatail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HandOfGod94/kafkatail/releases/download/v0.1.3/kafkatail_0.1.3_Linux_x86_64.tar.gz"
      sha256 "45cd9282727b8a57e4fbacaa6f6b9c2758daf1884eb9c12a25ee5fb031b36077"

      def install
        bin.install "kafkatail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HandOfGod94/kafkatail/releases/download/v0.1.3/kafkatail_0.1.3_Linux_arm64.tar.gz"
      sha256 "83b1030e7753603e32aec50d506eb27d469591a3cbabd585e51407ea8f4bc5ff"

      def install
        bin.install "kafkatail"
      end
    end
  end
end
